version: '3'

services:
  rasa_server:
    container_name: rasa_server
    ports:
      - 5005:5005
    image: rasa-server:0.0.1
    command:
      - run
      - --cors
      - "*"
    volumes:
      - ./endpoints.yml:/app/endpoints.yml
    depends_on:
      - action_server
  
  action_server:
    container_name: action_server
    environment:
      - MONGODB_URL_LOCAL=mongodb://mongo_db:27016
    expose:
      - 5055
    image: action-server:0.0.1
    volumes:
      - ./actions/actions.py:/app/actions/actions.py
      - ./actions/__init__.py:/app/actions/__init__.py
    depends_on:
      - mongo_db

  # MongoDB Container
  # mongo_db:
  #   container_name: mongo_db
  #   image: mongo:latest
  #   expose:
  #     - 27017
  #   ports:
  #     - 27016:27017
  #   volumes:
  #     - /media/sk/Drive/RASA/mongodb/data/db:/data/db