version: '3'

services:
  # Reverse proxy nginx server
  reverse_proxy:
    container_name: reverse_proxy
    image: nginx:stable
    depends_on:
      - rasa_server
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
    # nginx_ext_port:container_inter_port
      - 80:80
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - rasa_chatbot_network
  
  # Rasa core open source container
  rasa_server:
    container_name: rasa_server
    image: ghcr.io/marlabs-chatbot/rasa-server-img-prod:0.0.1
    env_file:
      - ./.local.env
    expose:
      - 5005
    command:
      - run
      - --enable-api
      - --cors
      - "*"
    # volumes:
      # - ./endpoints.yml:/app/endpoints.yml
    depends_on:
      - action_server
    networks:
      - rasa_chatbot_network
    deploy:
      restart_policy:
        condition: on-failure
  
  action_server:
    container_name: action_server
    image: ghcr.io/marlabs-chatbot/action-server-img-prod:0.0.1
    env_file:
      - ./.local.env
    expose:
      - 5055
    # volumes:
      # - ./actions/actions.py:/app/actions/actions.py
      # - ./actions/__init__.py:/app/actions/__init__.py
    depends_on:
      - mongo_db
    networks:
      - rasa_chatbot_network
    deploy:
      restart_policy:
        condition: on-failure


  # MongoDB database container
  mongo_db:
    container_name: mongo_db
    image: mongo:latest
    expose:
      - 27017
    ports:
      - 27017:27017
    volumes:
      - ../mongodb/db:/data/db
    environment:
      # provide your credentials here
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    # command: mongod
    networks:
      - rasa_chatbot_network
    deploy:
      restart_policy:
        condition: on-failure

networks:
  rasa_chatbot_network:
