version: '3'

services:
  # # Reverse proxy nginx server
  # reverse_proxy:
  #   container_name: reverse_proxy
  #   image: nginx:stable
  #   depends_on:
  #     - rasa_server
  #   volumes:
  #     - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
  #   ports:
  #   # nginx_ext_port:container_inter_port
  #     - 5005:5005
  #   deploy:
  #     restart_policy:
  #       condition: on-failure
  #   networks:
  #     - rasa_chatbot_network
  

  # Rasa core open source container
  rasa_server:
    container_name: rasa_server
    image: rasa-server-img-prod:0.0.1
    env_file:
      - ./.prod.env
    ports:
      - 5005:5005
    expose:
      - 5005
    command:
      - run
      - --enable-api
      - --cors
      - "*"
    depends_on:
      - action_server
    networks:
      - rasa_chatbot_network
    deploy:
      restart_policy:
        condition: on-failure
  
  # Rasa Action Server
  action_server:
    container_name: action_server
    image: action-server-img-prod:0.0.1
    env_file:
      - ./.prod.env
    expose:
      - 5055
    networks:
      - rasa_chatbot_network
    deploy:
      restart_policy:
        condition: on-failure

networks:
  rasa_chatbot_network:
