version: '3'

services:
  # Reverse proxy nginx server
  # nginx_server:
  #   container_name: nginx_server
  #   image: nginx-server-img-local:0.0.1
  #   depends_on:
  #     - rasa_server
  #   volumes:
  #     - ./nginxServer/reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
  #     - ./nginxServer/marlabsChatbotUI:/data
  #   ports:
  #   # nginx_ext_port:container_inter_port
  #     - 80:80
  #   deploy:
  #     restart_policy:
  #       condition: on-failure
  #   networks:
  #     - rasa_chatbot
  
  # Rasa core open source container
  rasa_server:
    container_name: rasa_server
    image: rasa-server-img-local:0.0.1
    env_file:
      - ./.local.env
    # expose:
    #   - 5005
    ports:
      - 5005:5005
    command:
      - run
      - --enable-api
      - --cors
      - "*"
      # - -p
      # - "5006"
    volumes:
      - ./endpoints.yml:/app/endpoints.yml
    depends_on:
      - action_server
    networks:
      - rasa_chatbot
    deploy:
      restart_policy:
        condition: on-failure
  
  action_server:
    container_name: action_server
    image: action-server-img-local:0.0.1
    env_file:
      - ./.local.env
    expose:
      - 5055
    # volumes:
      # - ./actions/actions.py:/app/actions/actions.py
      # - ./actions/__init__.py:/app/actions/__init__.py
    depends_on:
      - mongo_db
    networks:
      - rasa_chatbot
    deploy:
      restart_policy:
        condition: on-failure

  # MongoDB database container
  mongo_db:
    container_name: mongo_db
    image: mongo:latest
    expose:
      - 27017
    ports:
      - 27017:27017
    volumes:
      - ../mongodb/db:/data/db
    environment:
      # provide your credentials here
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    # command: mongod
    networks:
      - rasa_chatbot
    deploy:
      restart_policy:
        condition: on-failure

networks:
  rasa_chatbot:
    external: true
