version: '3'

services:
  # Reverse proxy nginx server
  reverse_proxy:
    container_name: reverse_proxy
    image: nginx:stable
    depends_on:
      - rasa_server
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
    # nginx_ext_port:container_inter_port
      - 80:80
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - rasa_chatbot_network
  

  # Rasa core open source container
  rasa_server:
    container_name: rasa_server
    expose:
      - 5005
    # ports:
      # - 5005:5005
    image: rasa-server-img:0.0.1
    command:
      - run
      - --cors
      - "*"
    volumes:
      - ./endpoints.yml:/app/endpoints.yml
    depends_on:
      - action_server
    networks:
      - rasa_chatbot_network
    deploy:
      # replicas: 1
      restart_policy:
        condition: on-failure
  

  # Rasa custom action server container
  action_server:
    container_name: action_server
    environment:
      - MONGODB_URL_LOCAL=mongodb://mongo_db:27016
    expose:
      - 5055
    image: action-server-img:0.0.1
    volumes:
      - ./actions/actions.py:/app/actions/actions.py
      - ./actions/__init__.py:/app/actions/__init__.py
    depends_on:
      - mongo_db
    networks:
      - rasa_chatbot_network
    deploy:
      restart_policy:
        condition: on-failure


  # MongoDB database container
  mongo_db:
    container_name: mongo_db
    image: mongo:latest
    expose:
      - 27017
    ports:
      - 27016:27017
    volumes:
      - /media/sk/Drive/RASA/mongodb/data/db:/data/db
    networks:
      - rasa_chatbot_network
    deploy:
      restart_policy:
        condition: on-failure


networks:
  rasa_chatbot_network